name: PyInstaller

on: [push]

jobs:
  buildMac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests esptool zeroconf PyQt5
    - name: build with pyinstaller
      run: |
        pyinstaller airrohr-flasher.spec
        ls
        ls dist
    - uses: actions/upload-artifact@v2
      with:
        name: airrohr-flasher
        path: dist/airrohr-flasher
        
  buildUbuntu20:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qttools5-dev-tools pyqt5-dev-tools qt5-default python3-pip python3.9 make
    - name: build with pyinstaller
      run: |
        make deps dist && ls dist/
    - uses: actions/upload-artifact@v2
      with:
        name: airrohr-flasher-ubuntu
        path: dist/airrohr-flasher

  buildUbuntuLatest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qttools5-dev-tools pyqt5-dev-tools qtbase5-dev qt5-qmake python3-pip python3.9 make
    - name: build with pyinstaller
      run: |
        make deps dist && ls dist/
    - uses: actions/upload-artifact@v2
      with:
        name: airrohr-flasher-ubuntu
        path: dist/airrohr-flasher
    
  buildWin:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build App
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests esptool zeroconf PyQt5
          pyinstaller airrohr-flasher.spec
          ls dist/
      - uses: actions/upload-artifact@v2
        with:
          name: airrohr-flasher-win
          path: dist/airrohr-flasher.exe
          
  buildWin19:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build App
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests esptool zeroconf PyQt5
          pyinstaller airrohr-flasher.spec
          ls dist/
      - uses: actions/upload-artifact@v2
        with:
          name: airrohr-flasher-win19
          path: dist/airrohr-flasher.exe
          
